# This is a config for E2B sandbox template.
# You can use template ID (d622vkz8p86647vfbfsu) or template name (vibe-nextjs-nandu) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-nandu") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-nandu") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-nandu')

team_id = "dd3a8ee6-8582-4e8c-8266-87090ff8d4a1"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-nandu"
template_id = "d622vkz8p86647vfbfsu"
